source "https://rubygems.org"

gem 'capistrano'
gem 'capistrano-simple-formatter'
gem 'capistrano-symfony'
gem 'capistrano-composer'
gem 'capistrano-copy-files'
gem 'capistrano-pending'
gem 'capistrano-lephare', github: 'le-phare/capistrano-lephare'
